//! Export the image back to `world/*.mst` text for source control
//! (`docs/IMAGE.md` §6) — a **surgical, in-place** update, not a from-scratch
//! regeneration.
//!
//! Why surgical: classes are *reopened* across many files (e.g. `28_point.mst`
//! reopens `Object`/`Number`/`Integer`), and the image merges every reopening
//! into one record with no file-provenance column. The FILES are therefore the
//! only record of "which method lives where", so we edit each method where it
//! already sits — replacing only the bodies that actually changed — and route
//! anything with no home (a class or method created in the GUI) to one
//! exporter-owned additions file. Consequences:
//!   - unchanged methods are byte-identical, so `git diff` shows exactly the
//!     interactive edits and nothing else;
//!   - re-exporting an unchanged image touches no file (idempotent);
//!   - the emitted `.mst` re-imports to the same image (round-trips).
//!
//! v1 scope: method-body edits + brand-new classes/methods. Not yet: exporting a
//! method DELETED in the image (left in its file), or a class-definition/ivar
//! edit (only method bodies are spliced). Those are follow-ups; the GUI outliner
//! — the main editing surface — only does method edits + add-class/add-method,
//! which this covers fully.

use crate::{mst, Image};
use std::collections::{HashMap, HashSet};
use std::fs;
use std::path::{Path, PathBuf};

/// The one file the exporter fully owns and regenerates: everything in the image
/// that has no home in a hand-authored `world/*.mst` lands here.
pub const ADDITIONS_FILE: &str = "50_image_additions.mst";

const ADDITIONS_HEADER: &str = "\"50_image_additions.mst — AUTO-GENERATED by the GUI's \
'Save World to Files' (image_store::export). Classes and methods created in the \
image (e.g. via the class browser) that don't yet live in a hand-authored world \
file are collected here so they can be reviewed and checked in. Move a definition \
into a topic file by hand and it will stay there on the next export.\"\n";

#[derive(Debug, Default, Clone, Copy, PartialEq, Eq)]
pub struct ExportStats {
    pub files_changed: usize,
    pub methods_updated: usize,
    pub methods_added: usize,
    pub classes_added: usize,
}

/// The `.mst` filenames named in `world.list`, in load order (comments and blank
/// lines skipped — same format `import_world_dir` reads). `world.list`, not a
/// directory glob, is the canonical world: a stray `.mst` isn't part of it.
fn read_world_list(world_dir: &Path) -> Result<Vec<String>, String> {
    let list_path = world_dir.join("world.list");
    let text = fs::read_to_string(&list_path)
        .map_err(|e| format!("reading {}: {e}", list_path.display()))?;
    Ok(text
        .lines()
        .map(|l| l.trim())
        .filter(|l| !l.is_empty() && !l.starts_with('#'))
        .map(|l| l.to_string())
        .collect())
}

/// Ensure the additions file is named in `world.list` (appended last, so its
/// reopenings see every earlier class) — otherwise the classes/methods the
/// exporter just wrote there would never re-import.
fn ensure_in_world_list(world_dir: &Path, entries: &[String]) -> Result<(), String> {
    if entries.iter().any(|e| e == ADDITIONS_FILE) {
        return Ok(());
    }
    let list_path = world_dir.join("world.list");
    let mut text = fs::read_to_string(&list_path).unwrap_or_default();
    if !text.ends_with('\n') {
        text.push('\n');
    }
    text.push_str(&format!(
        "\n# GUI-created classes/methods, collected by 'Save World to Files'.\n{ADDITIONS_FILE}\n"
    ));
    fs::write(&list_path, text).map_err(|e| format!("updating world.list: {e}"))
}

/// Write the image's current state over `world_dir`'s `.mst` files in place.
pub fn export_world_dir(image: &Image, world_dir: &Path) -> Result<ExportStats, String> {
    let entries = read_world_list(world_dir)?;
    // The hand-authored files (world.list minus the exporter-owned additions
    // file, which pass 2 regenerates wholesale).
    let files: Vec<PathBuf> = entries
        .iter()
        .filter(|n| n.as_str() != ADDITIONS_FILE)
        .map(|n| world_dir.join(n))
        .collect();

    // Pre-scan: `present` = every (class, side, selector) that lives in some
    // hand-authored file (anything NOT here is "new" → the additions file).
    // `last_occ` = the index of the LAST file (in load order) that defines each
    // method: a method reopened/overridden across files (e.g. TranscriptStream
    // >>show: is basic in 04_transcript, printString-aware in 19_printing) has
    // several occurrences, but the image holds only the effective (latest) one,
    // so only its LAST file may carry it — splicing the latest into an earlier
    // occurrence would wrongly overwrite an intentional override.
    let mut present: HashSet<(String, String, String)> = HashSet::new();
    let mut last_occ: HashMap<(String, String, String), usize> = HashMap::new();
    for (idx, f) in files.iter().enumerate() {
        let text =
            fs::read_to_string(f).map_err(|e| format!("reading {}: {e}", f.display()))?;
        for c in mst::parse_mst_source(&text) {
            for m in &c.methods {
                let side = if m.is_class_side { "class" } else { "instance" };
                let key = (c.name.clone(), side.to_string(), m.selector.clone());
                present.insert(key.clone());
                last_occ.insert(key, idx); // later file wins → last occurrence
            }
        }
    }

    let mut stats = ExportStats::default();

    // ── Pass 1: splice changed method bodies into the files that own them ──
    for (idx, f) in files.iter().enumerate() {
        let text =
            fs::read_to_string(f).map_err(|e| format!("reading {}: {e}", f.display()))?;
        let mut new_text = text.clone();
        for c in mst::parse_mst_source(&text) {
            for m in &c.methods {
                let side_str = if m.is_class_side { "class" } else { "instance" };
                let key = (c.name.clone(), side_str.to_string(), m.selector.clone());
                // Only the last file that defines this method carries its
                // effective source; earlier occurrences are intentional
                // overrides and stay exactly as written.
                if last_occ.get(&key) != Some(&idx) {
                    continue;
                }
                let side = if m.is_class_side {
                    crate::Side::Class
                } else {
                    crate::Side::Instance
                };
                let db = image
                    .method_source(&c.name, side, &m.selector)
                    .map_err(|e| format!("querying {}>>{}: {e}", c.name, m.selector))?;
                if let Some(db_src) = db {
                    if db_src != m.source {
                        // The parsed source is a verbatim, unique substring of the
                        // file (a selector can't repeat within a class), so a
                        // single find/replace is exact.
                        if let Some(pos) = new_text.find(&m.source) {
                            new_text.replace_range(pos..pos + m.source.len(), &db_src);
                            stats.methods_updated += 1;
                        }
                    }
                }
                // db == None → the method was deleted in the image; v1 leaves it.
            }
        }
        if new_text != text {
            fs::write(f, &new_text).map_err(|e| format!("writing {}: {e}", f.display()))?;
            stats.files_changed += 1;
        }
    }

    // ── Pass 2: regenerate the additions file from everything with no home ──
    let mut blocks = String::new();
    for c in image
        .all_classes()
        .map_err(|e| format!("listing classes: {e}"))?
    {
        let methods = image
            .all_methods_of(&c.name)
            .map_err(|e| format!("listing {}'s methods: {e}", c.name))?;
        let homeless: Vec<_> = methods
            .into_iter()
            .filter(|m| {
                !present.contains(&(c.name.clone(), m.side.as_str().to_string(), m.selector.clone()))
            })
            .collect();
        if homeless.is_empty() {
            continue;
        }
        // A class with NO methods in any hand-authored file is itself new, so it
        // needs its full definition (ivars/classVars); a class merely gaining a
        // method is reopened with just that method.
        let is_new_class = !present.iter().any(|(cls, _, _)| cls == &c.name);
        if is_new_class {
            stats.classes_added += 1;
        }
        stats.methods_added += homeless.len();

        let superclass = c.superclass.as_deref().unwrap_or("Object");
        blocks.push_str(&format!("{superclass} subclass: {} [\n", c.name));
        if is_new_class {
            if !c.instance_vars.trim().is_empty() {
                blocks.push_str(&format!("    | {} |\n", c.instance_vars.trim()));
            }
            if !c.class_vars.trim().is_empty() {
                blocks.push_str(&format!("    <classVars: {}>\n", c.class_vars.trim()));
            }
        }
        for m in &homeless {
            // Stored source is already in class-block form (instance methods bare,
            // class methods carrying their `Name class >>` prefix), so emit as-is.
            for line in m.source.trim_end().lines() {
                blocks.push_str("    ");
                blocks.push_str(line);
                blocks.push('\n');
            }
        }
        blocks.push_str("]\n\n");
    }

    let additions_path = world_dir.join(ADDITIONS_FILE);
    let existing = fs::read_to_string(&additions_path).unwrap_or_default();
    if blocks.is_empty() {
        // Nothing homeless: leave a header-only file (or none) so a stale export
        // doesn't linger, but only touch disk if it actually changes.
        if additions_path.exists() && !existing.is_empty() {
            fs::write(&additions_path, "")
                .map_err(|e| format!("clearing {}: {e}", additions_path.display()))?;
            stats.files_changed += 1;
        }
    } else {
        let content = format!("{ADDITIONS_HEADER}\n{blocks}");
        if existing != content {
            fs::write(&additions_path, &content)
                .map_err(|e| format!("writing {}: {e}", additions_path.display()))?;
            stats.files_changed += 1;
        }
        // Make sure it re-imports next time.
        ensure_in_world_list(world_dir, &entries)?;
    }

    Ok(stats)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{Image, Side};

    #[test]
    fn export_is_idempotent_splices_edits_and_homes_new_methods() {
        let dir = std::env::temp_dir().join(format!("macvm_export_{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();

        // A tiny hand-authored world file.
        let foo = "\"a comment\"\nObject subclass: Foo [\n    | x |\n    bump [\n        x := x + 1\n    ]\n    x [\n        ^x\n    ]\n]\n";
        fs::write(dir.join("10_foo.mst"), foo).unwrap();
        fs::write(dir.join("world.list"), "10_foo.mst\n").unwrap();

        let image = Image::open(&dir.join("image.sqlite3")).unwrap();
        crate::import::import_world_dir(&image, &dir).unwrap();

        // 1) Idempotent: image matches files → export is a no-op, byte-for-byte.
        assert_eq!(
            export_world_dir(&image, &dir).unwrap(),
            ExportStats::default(),
            "a fresh export must touch nothing"
        );
        assert_eq!(
            fs::read_to_string(dir.join("10_foo.mst")).unwrap(),
            foo,
            "unchanged file stays byte-identical"
        );

        // 2) Edit a method in the image → spliced into the owning file, alone.
        image
            .set_method_source("Foo", Side::Instance, "x", "x [\n        ^x ifNil: [ 0 ]\n    ]")
            .unwrap();
        let s = export_world_dir(&image, &dir).unwrap();
        assert_eq!(
            (s.files_changed, s.methods_updated),
            (1, 1),
            "exactly one edit spliced, got {s:?}"
        );
        let after = fs::read_to_string(dir.join("10_foo.mst")).unwrap();
        assert!(after.contains("ifNil: [ 0 ]"), "edited body present: {after}");
        assert!(after.contains("bump ["), "untouched method preserved: {after}");
        // Idempotent again after the edit.
        assert_eq!(export_world_dir(&image, &dir).unwrap(), ExportStats::default());

        // 3) A brand-new method with no home lands in the additions file.
        image
            .create_or_reopen_method("Foo", Side::Instance, "reset", "", "reset [\n        x := 0\n    ]")
            .unwrap();
        let s = export_world_dir(&image, &dir).unwrap();
        assert_eq!(s.methods_added, 1, "one homeless method, got {s:?}");
        let adds = fs::read_to_string(dir.join(ADDITIONS_FILE)).unwrap();
        assert!(adds.contains("Object subclass: Foo ["), "reopening block: {adds}");
        assert!(adds.contains("reset ["), "new method in additions: {adds}");

        // 4) Round-trip: re-import the exported tree → same method sources.
        let image2 = Image::open(&dir.join("image2.sqlite3")).unwrap();
        crate::import::import_world_dir(&image2, &dir).unwrap();
        assert_eq!(
            image2.method_source("Foo", Side::Instance, "x").unwrap(),
            image.method_source("Foo", Side::Instance, "x").unwrap(),
            "edited method round-trips"
        );
        assert!(
            image2
                .method_source("Foo", Side::Instance, "reset")
                .unwrap()
                .is_some(),
            "added method round-trips"
        );

        let _ = fs::remove_dir_all(&dir);
    }
}
